amp_enabled: true
backbone: resnet18
batch_size: 8
best_model_epoch: 4
best_val_loss: 0.2772303479288473
class_names:
- background
- pole
- trunk
- vine_row
dataset_root: dataset_gps_masks_with_augmentations/riseholme/patches_480x640
device: cuda
early_stopping_patience: 20
image_size: !!python/tuple
- 640
- 480
last_trained_epoch: 24
learning_rate: 0.0001
loss_function: CrossEntropyLoss
model_output_path: resnet18_unet_image_size_640x480_batch_size_8.pth
num_classes: 4
num_epochs: 100
optimizer: Adam
timestamp: '2025-10-29 09:28:40'
