amp_enabled: true
backbone: resnet18
batch_size: 8
best_model_epoch: 3
best_val_loss: 0.09660695105045752
class_names:
- background
- pole
- trunk
- vine_row
dataset_root: heatmap_masks_from_yolo_labels/vineyard_segmentation_21
device: cuda
early_stopping_patience: 20
image_size: !!python/tuple
- 1014
- 760
last_trained_epoch: 23
learning_rate: 0.0001
loss_function: CrossEntropyLoss
model_output_path: resnet18_unet_image_size_1014x760_batch_size_8.pth
num_classes: 4
num_epochs: 100
optimizer: Adam
timestamp: '2025-10-31 15:34:42'
